// Display-only translations for metadata directory and tag names shown in the info page.
// Names that are not mapped fall back to the original (English) text.

const Map<String, String> _metadataDirNameZh = {
  'Exif IFD0': 'Exif 基本信息',
  'Exif IFD1': 'Exif 缩略图',
  'GPS': '位置信息 (GPS)',
  'ICC Profile': '色彩配置 (ICC)',
  'JFIF': 'JPEG 基本信息 (JFIF)',
  'PNG': 'PNG 图像信息',
  'HEIF': 'HEIF 图像信息',
  'WebP': 'WebP 图像信息',
  'XMP': 'XMP 元数据',
  'IPTC': 'IPTC 信息',
  'Interoperability': 'Exif 互操作信息',
  'File Type': '文件类型',
  'Huffman': '霍夫曼编码表',
  'Adobe': 'Adobe 信息',
  'Photoshop': 'Photoshop 信息',
  'PrintIM': '打印信息 (PrintIM)',
  'QuickTime': '视频元数据 (QuickTime)',
  'MP4': '视频元数据 (MP4)',
  'Matroska': '视频元数据 (Matroska)',
  'Media': '媒体信息',
};

const Map<String, String> _metadataDirPrefixZh = {
  'Exif SubIFD': 'Exif 拍摄参数',
  'Exif Thumbnail': 'Exif 缩略图',
  'MPF Image #': 'MPF 图像 #',
  'Canon': '佳能厂商信息',
  'Nikon': '尼康厂商信息',
  'Sony': '索尼厂商信息',
  'Fujifilm': '富士厂商信息',
  'Panasonic': '松下厂商信息',
  'Olympus': '奥林巴斯厂商信息',
  'Samsung': '三星厂商信息',
  'ISO BMFF': '视频容器信息',
};

const Map<String, String> _metadataTagNameZh = {
  // common image properties
  'Image Width': '图像宽度',
  'Image Height': '图像高度',
  'Bit Depth': '位深',
  'Bits Per Sample': '位深',
  'Color Type': '颜色类型',
  'Compression': '压缩方式',
  'Compression Type': '压缩类型',
  'Filter Method': '滤波方式',
  'Interlace Method': '隔行方式',
  'Background Color': '背景色',
  'Textual Data': '文本数据',
  'Last Modification Time': '修改时间',
  'Uniform Resource Identifier': '资源标识符',
  'Auxiliary Image Type': '辅助图像类型',
  'Is Primary': '主图',
  'Rotation': '旋转',
  'Width': '宽度',
  'Height': '高度',
  'Duration': '时长',
  'Frame Rate': '帧率',
  'Codec': '编码格式',
  'Creation Time': '创建时间',
  'Modification Time': '修改时间',
  'Major Brand': '主品牌',
  'Minor Version': '次要版本',
  'Compatible Brands': '兼容品牌',
  'Handler Type': '处理器类型',
  'Track ID': '轨道 ID',
  'Track Duration': '轨道时长',
  'Media Duration': '媒体时长',
  'Media Time Scale': '媒体时间刻度',
  'Media Language Code': '语言代码',
  // Exif IFD0
  'Make': '相机厂商',
  'Model': '相机型号',
  'Orientation': '方向',
  'Resolution Unit': '分辨率单位',
  'X Resolution': 'X 分辨率',
  'Y Resolution': 'Y 分辨率',
  'YCbCr Positioning': 'YCbCr 定位',
  'Date/Time': '文件修改时间',
  'Artist': '作者',
  'Copyright': '版权',
  'Software': '软件',
  'Page Number': '页码',
  'Document Name': '文档名称',
  'Host Computer': '主机信息',
  // Exif SubIFD
  'Exif Version': 'Exif 版本',
  'FlashPix Version': 'FlashPix 版本',
  'Date/Time Original': '拍摄时间',
  'Date/Time Digitized': '数字化时间',
  'Sub-Sec Time': '亚秒时间',
  'Sub-Sec Time Original': '拍摄亚秒时间',
  'Sub-Sec Time Digitized': '数字化亚秒时间',
  'Components Configuration': '分量配置',
  'Compressed Bits Per Pixel': '压缩位率',
  'Exposure Time': '曝光时间',
  'F Number': '光圈值',
  'Exposure Program': '曝光程序',
  'ISO': '感光度',
  'Sensitivity Type': '感光度类型',
  'Recommended Exposure Index': '推荐感光度',
  'Exif Version ': 'Exif 版本',
  'Shutter Speed Value': '快门速度',
  'Aperture Value': '光圈值',
  'Brightness Value': '亮度值',
  'Exposure Bias Value': '曝光补偿',
  'Exposure Index': '曝光指数',
  'Max Aperture Value': '最大光圈',
  'Subject Distance': '对焦距离',
  'Subject Distance Range': '对焦距离范围',
  'Metering Mode': '测光模式',
  'Light Source': '光源',
  'White Balance': '白平衡',
  'Flash': '闪光灯',
  'Focal Length': '焦距',
  'Focal Length In 35mm Format': '等效 35mm 焦距',
  'Scene Capture Type': '场景类型',
  'Scene Mode': '场景模式',
  'Digital Zoom Ratio': '数码变焦倍数',
  'Contrast': '对比度',
  'Saturation': '饱和度',
  'Sharpness': '锐度',
  'Gain Control': '增益控制',
  'Custom Rendered': '自定义处理',
  'Sensing Method': '感光元件类型',
  'File Source': '文件来源',
  'Color Space': '色彩空间',
  'Exif Image Width': 'Exif 图像宽度',
  'Exif Image Height': 'Exif 图像高度',
  'User Comment': '用户注释',
  'Lens Make': '镜头厂商',
  'Lens Model': '镜头型号',
  'Lens Specification': '镜头参数',
  'Lens Serial Number': '镜头序列号',
  'Body Serial Number': '机身序列号',
  // GPS
  'GPS Version ID': 'GPS 版本',
  'GPS Latitude Ref': 'GPS 纬度参考',
  'GPS Latitude': 'GPS 纬度',
  'GPS Longitude Ref': 'GPS 经度参考',
  'GPS Longitude': 'GPS 经度',
  'GPS Altitude Ref': 'GPS 高度参考',
  'GPS Altitude': 'GPS 海拔',
  'GPS Time Stamp': 'GPS 时间',
  'GPS Date Stamp': 'GPS 日期',
  'GPS Speed Ref': 'GPS 速度参考',
  'GPS Speed': 'GPS 速度',
  'GPS Direction Ref': 'GPS 方向参考',
  'GPS Direction': 'GPS 方向',
  'GPS Img Direction Ref': '拍摄方向参考',
  'GPS Img Direction': '拍摄方向',
  'GPS Processing Method': 'GPS 定位方式',
  'GPS H Positioning Error': 'GPS 水平误差',
  'GPS Dest Latitude Ref': '目的地纬度参考',
  'GPS Dest Latitude': '目的地纬度',
  'GPS Dest Longitude Ref': '目的地经度参考',
  'GPS Dest Longitude': '目的地经度',
  // ICC
  'ICC Profile Version': 'ICC 版本',
  'Color Space Data': '色彩空间数据',
  'Profile Connection Space': '连接空间',
  'Device Manufacturer': '设备制造商',
  'Device Model': '设备型号',
  'Media White Point': '白点',
  'Primary Platform': '主平台',
  'CMM Flags': 'CMM 标志',
  'Rendering Intent': '渲染意图',
  'Profile Copyright': '配置版权',
  'Profile Date/Time': '配置时间',
  'Profile Description': '配置描述',
  'ICC Profile Name': 'ICC 配置名称',
  // JFIF
  'Version': '版本',
  'Resolution Units': '分辨率单位',
  'Thumbnail Width': '缩略图宽度',
  'Thumbnail Height': '缩略图高度',
  // PNG
  'Suggested Palette Entry': '建议调色板',
  'Display Window': '显示窗口',
  // video
  'Time Scale': '时间刻度',
  'Canvas': '画布尺寸',
};

String metadataDirNameZh(String name) {
  final exact = _metadataDirNameZh[name];
  if (exact != null) return exact;
  for (final kv in _metadataDirPrefixZh.entries) {
    if (name.startsWith(kv.key)) return kv.value;
  }
  return name;
}

String metadataTagNameZh(String name) => _metadataTagNameZh[name] ?? name;
